"""AgentCore Platform v1.0"""

# State must be a flat TypedDict — never a Pydantic model. Graph checkpoints use
# msgpack serialisation and model instances corrupt silently there. Extend
# AgentState with agent-specific fields only, and never add credentials or
# secrets.
#
# SVC-C2-010 — Professional Services Operations & Billing Anomaly Detection Agent
# Two-layer nested Cat 2 graph: outer backbone (AgentBaseGraph) + inner domain
# workflow (BaseGraph). The fields below cover both layers.
#
# Caller data travels on `caller_payload`, not on user_input / validated_input.
# The platform's input gate masks personal-name-shaped text on those two fields in
# place, so an engagement label carried there reaches the pipeline rewritten. The
# payload is validated in InputValidateNode before it is written here, and every
# string in it is an inert bounded identifier.

from typing import Any, Dict, List, Optional

from framework.schemas.agent_state import AgentState


class State(AgentState):
    """Flat TypedDict for SVC-C2-010.

    All shared fields (user_input, status, session_id, node_history, error_log,
    hitl_*, etc.) are inherited from AgentState.
    """

    # ------------------------------------------------------------------
    # Outer layer — set by InputValidateNode (pre_process backbone)
    # ------------------------------------------------------------------

    # Short, inert summary of the accepted request. This is the framework-visible
    # copy; it carries no free text, so the platform's masking cannot alter
    # anything the pipeline depends on.
    validated_input: Optional[str]

    # The validated operations payload — the channel the pipeline actually reads.
    # Structure: {engagement_id, billing_period, metrics: {...},
    #             baseline_metrics: {...} | None, team_size: float | None}
    caller_payload: Optional[Dict[str, Any]]

    # Channel / request metadata (never contains personal data).
    enriched_context: Optional[Dict[str, Any]]

    # Validated runtime settings from config/config.yaml, seeded into the initial
    # state so the nodes read a live declaration rather than a private default.
    runtime_settings: Optional[Dict[str, Any]]

    # ------------------------------------------------------------------
    # Inner layer — domain nodes (DomainWorkflowGraph)
    # ------------------------------------------------------------------

    # Parsed billing & operations metrics payload, as accepted from the caller.
    operations_data: Optional[Dict[str, Any]]

    # Baseline metrics the deviations are measured against.
    # Keyed by metric name, matching operations_data["metrics"].
    baseline_data: Optional[Dict[str, float]]

    # Where each baseline came from: "caller_history" | "benchmark".
    # Rendered as provenance so a reader can tell a measured baseline from a
    # standard one.
    baseline_sources: Optional[Dict[str, str]]

    # Metrics carrying no baseline at all, and therefore excluded from analysis.
    unbaselined_metrics: Optional[List[str]]

    # Deviation records comparing current vs baseline per metric.
    # Each entry: {metric, current, baseline, deviation_pct, threshold_exceeded}
    deviations: Optional[List[Dict[str, Any]]]

    # Classified anomaly findings.
    # Each entry: {type, severity, metric, current_value, baseline_value,
    #              deviation_pct, description}
    anomaly_classifications: Optional[List[Dict[str, Any]]]

    # Total number of anomalies detected (counts all severities).
    anomaly_count: Optional[int]

    # Aggregate alert severity: "critical" | "high" | "medium" | "normal".
    alert_severity: Optional[str]

    # Structured management alert generated by GenerateManagementAlertNode.
    management_alert: Optional[Dict[str, Any]]

    # ------------------------------------------------------------------
    # Outer layer — set by OutputFormatNode (post_process backbone)
    # ------------------------------------------------------------------

    # Final formatted alert text returned to the caller. Always non-empty: on a
    # withheld result it carries the refusal notice, never an empty string, which
    # would re-open the framework's fallback to the un-gated inner answer.
    formatted_output: Optional[str]

    # ------------------------------------------------------------------
    # Tracing / audit — framework-managed; do NOT write from node code
    # ------------------------------------------------------------------

    trace_id: Optional[str]
    correlation_id: Optional[str]
    # Set when a run COMPLETES without carrying out the request, because the
    # caller sent a value they can correct. A closed set of codes, never caller
    # content. Nodes downstream of the one that set it do no work and pass it on.
    error_code: Optional[str]
    # node_history inherited from AgentState
